### ISSUE TITLE
rclone automation

### ISSUE THREAD

**Issue by thu4n** [SVUIT/mmtt#178]
Sử dụng GitHub Actions để tự động hóa việc chạy rclone backup google drive hàng tuần

**Comment by locnh8** [comment]
@VietHoang-206 tìm hiểu trước Rclone và Ubuntu WSL.
Docs:
- rclone: https://rclone.org/
- Ubuntu WSL: https://documentation.ubuntu.com/wsl/en/latest/

**Comment by VietHoang-206** [comment]
Tìm hiểu được cơ bản về cách hoạt động của GIT và rclone.
Đang tiếp tục tìm hiểu về Github Action.

**Comment by thu4n** [comment]
Ok, với GitHub Actions thì em có thể bắt đầu bằng việc tìm hiểu định dạng file YAML nhe @VietHoang-206 , do nó hoạt động dựa trên file đó á

**Comment by locnh8** [comment]
Đã thực hiện thành công. Link tham khảo: https://github.com/marketplace/actions/setup-rclone-action
