### ISSUE TITLE
Up tài liệu và viết mô tả cho các môn đại cương còn thiếu

### ISSUE THREAD

**Issue by thu4n** [SVUIT/mmtt#66]
@nhloc8 Em dạo một vòng drive của mình, thấy môn nào còn thiếu hoặc là chưa có thì bổ sung. Sau đó em reply ở đây những môn học mà em đã thêm để các anh check. Sau đó, bắt đầu viết file markdown mô tả các môn học này.

**Comment by nhloc8** [comment]
13/3
-  Chỉnh sửa và bổ sung gg drive PH002 - Mạch số K17, thêm note vào Mạch số K18.
-  Thêm markdown môn học PH002 - Mạch số.

**Comment by thu4n** [comment]
Well done.
