### ISSUE TITLE
Viết bài đăng fanpage Facebook và release tag mới trên GitHub

### ISSUE THREAD

**Issue by thu4n** [SVUIT/mmtt#78]
- Bài đăng fanpage tập trung vào việc thông báo full đại cương và cơ sở ngành,  điểm nhấn là oop và dsa.
- Release tag v1.0.3, liệt kê những thay đổi đáng kể về môn học và trang web (né những thay đổi cũ của version trước).

**Comment by nhloc8** [comment]
- Đã release tag v1.0.3
- Đã viết xong bài đăng cho fanpage
