### ISSUE TITLE
Thêm chú thích môn học tiên quyết, môn học trước cho các môn học trên website

### ISSUE THREAD

**Issue by thu4n** [SVUIT/mmtt#79]
Format của chú thích đã được cập nhật ở [file README](https://github.com/SVUIT/mmtt/blob/main/README.md). Anh Hải cứ xem qua rồi triển thôi.

**Comment by Ahamonuser** [comment]
TODO:
IT002: học trước IT001
IT003: học trước IT001
IT006: học trước IT001, PH002
IT007: học trước IT006
MA005: học trước MA006
NT101: học trước IT005
NT105: học trước IT005
NT106: học trước IT001, IT005
NT113: học trước NT132
NT118: học trước IT002
NT131: học trước IT007
NT132: học trước IT005
NT330: học trước NT101
NT533: học trước IT005
NT538: học trước IT005
NT539: học trước IT005

**Comment by Ahamonuser** [comment]
NOTE:
IT001 - Nhập môn lập trình
IT002 - Lập trình hướng đối tượng
IT005 - Nhập môn mạng máy tính
IT006 - Kiến trúc máy tính
IT007 - Hệ điều hành
MA006 - Giải tích
NT101 - An toàn mạng máy tính
NT132 - Quản trị mạng và hệ thống
PH002 - Nhập môn mạch số

**Comment by Ahamonuser** [comment]
IT002, IT003 (MonHocDaiCuong) done

**Comment by Ahamonuser** [comment]
IT006, IT007, NT101, NT105, NT106, NT113, NT118, NT131, NT132 (MonHocCoSoNganh) done

**Comment by Ahamonuser** [comment]
NT533, NT538 (MonHocChuyenNganh) done

**Comment by Ahamonuser** [comment]
NT330, NT539 (MonHocTuChon) done

**Comment by Ahamonuser** [comment]
hình như page còn thiếu MA005 - Xác suất thống kê thì phải

**Comment by Ahamonuser** [comment]
ko thấy MA005.md đâu cả

**Comment by Ahamonuser** [comment]
![image](https://github.com/SVUIT/mmtt/assets/116050616/b2defd00-fd32-4e3d-a7fc-e7a2b20f39e5)
theo như web là cần đấy

**Comment by Ahamonuser** [comment]
MA005 (MonHocDaiCuong) done
