### ISSUE TITLE
Upload video lên kênh Youtube

### ISSUE THREAD

**Issue by thu4n** [SVUIT/mmtt#95]
- Link kênh Youtube: https://www.youtube.com/@svuit-mmtt
- Link video giả chứa định dạng tiêu đề: https://www.youtube.com/playlist?list=PLzGbLqPJwYz1KdrLlHW5Vwj47w-9l1G1M
- Lưu ý: Sau khi upload video, cần add chúng vào **danh sách phát** tương ứng với môn học đó.
- Các video nào cần cắt ghép gì đó thì liên hệ @thu4n (upload lên drive chia sẻ rồi gửi link qua hoặc copy usb)
- Cố gắng hoàn thành trước **30/04/2024**
- Các môn học cần upload và phân công cụ thể như sau:
  - NT131 - 3 thg k16
  - NT118 - 3 thg K16
  - NT101 - @thu4n 
  - NT532 - 3 thg K16
  - NT536 - @thu4n 
  - NT132 - @thu4n 
  -  NT106 - @thu4n , @r1anl3

**Comment by Ahamonuser** [comment]
Note:
NT131 - Hệ thống nhúng Mạng không dây

**Comment by Ahamonuser** [comment]
@thu4n @r1anl3 thiết nghĩ nên chuyển tên thành viên vô phần mô tả như ở vài vid @thu4n đã up nhở

**Comment by thu4n** [comment]
Yeah, các tên thành viên nên để hết vô phần mô tả đi chứ title ko đủ chỗ đâu
