### ISSUE TITLE
Tạo Microsoft Form cho phép đóng góp tài liệu

### ISSUE THREAD

**Issue by thu4n** [SVUIT/mmtt#97]
Sử dụng mail `@ms.uit.edu.vn` của trường cấp để tạo một Microsoft Form, yêu cầu chung như sau:
- Cho phép đăng tải mọi loại file, số lượng tối đa là 10, kích thước tối đa là 1 Gb.
- Không lưu trữ email người điền form nhưng cho phép họ nhận receipt từ submit của mình.
- Cần có mail thông báo cho mỗi lượt điền form.
- Sẽ có option để họ điền tên mình vào nhưng không bắt buộc (tức cho phép submit ẩn danh).

**Comment by thu4n** [comment]
Nên có 1 option cho phép họ ghi chú gì đó trong submit

**Comment by nhloc8** [comment]
Có cần mục tên môn học cho dễ phân loại không anh? mà nếu vậy thì đóng góp nhiều file thì khó cho người dùng.

**Comment by nhloc8** [comment]
https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=rAn_LTsrgkGZUytUjg0LOZCfeRzfZLFBh8X3EGL6N5BUNFJVOFBBMkI2NDhDMklaQzA5V1pNR0tFMS4u&Token=67a3d2a44f5c4f00aee3d45cbae480bc

**Comment by thu4n** [comment]
> Có cần mục tên môn học cho dễ phân loại không anh? mà nếu vậy thì đóng góp nhiều file thì khó cho người dùng. 

Nên có mục cho phép người dùng viết một đoạn mô tả những tài liệu có trong file submit của họ (bao gồm tên môn và loại tài liệu)

**Comment by thu4n** [comment]
> https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=rAn_LTsrgkGZUytUjg0LOZCfeRzfZLFBh8X3EGL6N5BUNFJVOFBBMkI2NDhDMklaQzA5V1pNR0tFMS4u&Token=67a3d2a44f5c4f00aee3d45cbae480bc

![image](https://github.com/SVUIT/mmtt/assets/53972592/761ed6c6-c534-416a-bafc-12cddd83e56b)

Cần thêm một số nội dung mô tả về form nhe em. Giới thiệu form này dùng cho việc gì, quá nhiều file thì phải như thế nào, ...

Hiện tại phần header còn hơi trống, để anh xem xét làm một cái hình banner cho form này.

**Comment by nhloc8** [comment]
https://forms.office.com/r/atPz47MttN
Anh xem qua thử nha anh.
