### ISSUE TITLE
Viết content thông báo kênh Youtube

### ISSUE THREAD

**Issue by thu4n** [SVUIT/mmtt#99]
Nội dung cần có:
- Giới thiệu về tên kênh youtube và các nội dung chính sẽ có trên kênh (đồ án, thực hành, chia sẻ kiến thức)
- Giới thiệu Form submit tài liệu.
- Kêu gọi đóng góp và đăng ký kênh.

**Comment by nhloc8** [comment]
Link đến đóng góp tài liệu mình để thẳng link đến ms form hay để link vào website cho người dùng click vào form ạ?

**Comment by thu4n** [comment]
Link này nhe em: https://[svuit.github.io/mmtt/docs/Submit/](https://svuit.github.io/mmtt/docs/Submit/)
